import {
  Activity,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Bot,
  Box,
  Check,
  ChevronDown,
  ChevronRight,
  Copy,
  Download,
  ExternalLink,
  File,
  Folder,
  GitBranch,
  Hash,
  Home,
  Inbox,
  LogOut,
  Menu,
  Mic,
  MessageCircle,
  MessageSquarePlus,
  MessageSquareText,
  PackageOpen,
  PanelsTopLeft,
  Play,
  Plus,
  Quote,
  RotateCcw,
  Search,
  Send,
  Settings,
  Share2,
  Sparkles,
  Square,
  ThumbsDown,
  ThumbsUp,
  TriangleAlert,
  UserRound,
  UsersRound,
  Waves,
  X,
  type LucideIcon,
} from "@lucide/svelte";

export const iconMap = {
  activity: Activity,
  agents: Bot,
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  artifacts: Box,
  bell: Bell,
  check: Check,
  chevron: ChevronRight,
  "chevron-down": ChevronDown,
  copy: Copy,
  download: Download,
  "external-link": ExternalLink,
  file: File,
  cube: PackageOpen,
  folder: Folder,
  hash: Hash,
  home: Home,
  inbox: Inbox,
  logout: LogOut,
  menu: Menu,
  mic: Mic,
  message: MessageCircle,
  "new-message": MessageSquarePlus,
  play: Play,
  plus: Plus,
  quote: Quote,
  retry: RotateCcw,
  repos: GitBranch,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  spark: Sparkles,
  stop: Square,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  workspace: PanelsTopLeft,
  warning: TriangleAlert,
  user: UserRound,
  users: UsersRound,
  waves: Waves,
  close: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export const fallbackIcon = MessageSquareText;
