/**
 * Presentation contracts: A2UI catalog, conversation projections, and composite
 * view-model schemas defined in protocol.ts.
 * Must not depend on daemon-only control-plane modules directly.
 */
export const SPARK_PROTOCOL_PRESENTATION_SUBPATH = "presentation" as const;

export * from "./a2ui.ts";
export * from "./conversation.ts";
export * from "./action-bars.ts";
export * from "./tool-display.ts";

// Composite view-model schemas/parsers that live in protocol.ts.
export {
  SPARK_ARTIFACT_PROJECTION_MAX_INLINE_BYTES,
  createBlockedInteractionResponse,
  parseSparkAskAcknowledgement,
  parseSparkDaemonEvent,
  parseSparkInteractionCapabilities,
  parseSparkInteractionRequest,
  parseSparkInteractionResponse,
  parseSparkSessionView,
  parseSparkViewModelEvent,
  sparkApprovalInteractionResponseSchema,
  sparkArtifactProjectionContentRefSchema,
  sparkArtifactProjectionSchema,
  sparkArtifactViewSchema,
  sparkAskAcknowledgementSchema,
  sparkAskFlowInteractionRequestSchema,
  sparkAskFlowInteractionResponseSchema,
  sparkAskOptionViewSchema,
  sparkAskQuestionViewSchema,
  sparkInteractionCapabilitiesSchema,
  sparkConfirmationInteractionRequestSchema,
  sparkConversationPartSchema,
  sparkConversationPartStatusSchema,
  sparkDaemonArtifactProjectedEventSchema,
  sparkDaemonDelegationRequestedEventSchema,
  sparkDaemonDelegationRespondedEventSchema,
  sparkDaemonEventSchema,
  sparkDaemonInteractionRequestEventSchema,
  sparkDaemonInteractionResponseEventSchema,
  sparkDaemonSessionUpdatedEventSchema,
  sparkDaemonTaskLifecycleEventSchema,
  sparkDaemonViewEventSchema,
  sparkDiffApprovalInteractionRequestSchema,
  sparkEvidenceViewSchema,
  sparkImageConversationPartSchema,
  sparkInteractionBaseRequestSchema,
  sparkInteractionRequestSchema,
  sparkInteractionResponseSchema,
  sparkIsoDateTimeSchema,
  sparkJsonObjectSchema,
  sparkJsonValueSchema,
  sparkMessageRoleSchema,
  sparkMessageStatusSchema,
  sparkMessageViewSchema,
  sparkModelSelectInteractionRequestSchema,
  sparkModelSelectInteractionResponseSchema,
  sparkModelSelectOptionSchema,
  sparkProtocolVersionSchema,
  sparkRefSchema,
  sparkRunStatusSchema,
  sparkRunViewSchema,
  sparkSessionGoalWorkViewSchema,
  sparkSessionMailChannelDeliveryViewSchema,
  sparkSessionMailMessageViewSchema,
  sparkSessionPrimaryWorkViewSchema,
  sparkSessionReproCurrentStepViewSchema,
  sparkSessionReproWorkViewSchema,
  sparkSessionSnapshotHistorySchema,
  sparkSessionSnapshotPageSchema,
  sparkSessionUsageSchema,
  sparkSessionVerificationReceiptViewSchema,
  sparkSessionViewSchema,
  sparkSessionWorkViewSchema,
  sparkTaskTodoViewSchema,
  sparkTaskViewSchema,
  sparkTaskViewStatuses,
  sparkTextConversationPartPhaseSchema,
  sparkTextConversationPartSchema,
  sparkTextPhaseFromSignature,
  sparkThinkingConversationPartSchema,
  sparkToolApprovalInteractionRequestSchema,
  sparkToolCallConversationPartSchema,
  sparkToolCallStatusSchema,
  sparkToolCallViewSchema,
  sparkToolResultConversationPartSchema,
  sparkViewModelEventSchema,
  sparkViewModelStatusSchema,
  sparkWorkflowPickerInteractionRequestSchema,
  sparkWorkflowPickerInteractionResponseSchema,
  sparkWorkflowPickerOptionSchema,
} from "./protocol.ts";

export type {
  SparkArtifactProjection,
  SparkArtifactProjectionContentRef,
  SparkArtifactView,
  SparkAskAcknowledgement,
  SparkAskQuestionView,
  SparkConversationPart,
  SparkConversationPartStatus,
  SparkDaemonArtifactProjectedEvent,
  SparkDaemonDelegationRequestedEvent,
  SparkDaemonDelegationRespondedEvent,
  SparkDaemonEvent,
  SparkDaemonInteractionRequestEvent,
  SparkDaemonInteractionResponseEvent,
  SparkDaemonSessionUpdatedEvent,
  SparkDaemonTaskLifecycleEvent,
  SparkDaemonViewEvent,
  SparkEvidenceView,
  SparkImageConversationPart,
  SparkInteractionCapabilities,
  SparkInteractionRequest,
  SparkInteractionResponse,
  SparkJsonObject,
  SparkJsonValue,
  SparkMessageRole,
  SparkMessageStatus,
  SparkMessageView,
  SparkRunView,
  SparkSessionGoalWorkView,
  SparkSessionMailChannelDeliveryView,
  SparkSessionMailMessageView,
  SparkSessionPrimaryWorkView,
  SparkSessionReproCurrentStepView,
  SparkSessionReproWorkView,
  SparkSessionSnapshotHistory,
  SparkSessionSnapshotPage,
  SparkSessionUsage,
  SparkSessionVerificationReceiptView,
  SparkSessionView,
  SparkSessionWorkView,
  SparkTaskTodoView,
  SparkTaskView,
  SparkTextConversationPart,
  SparkTextConversationPartPhase,
  SparkThinkingConversationPart,
  SparkToolCallConversationPart,
  SparkToolCallView,
  SparkToolResultConversationPart,
  SparkViewModelEvent,
  SparkViewModelStatus,
} from "./protocol.ts";
