/**
 * Local RPC implementation barrel — domain modules live beside this file.
 * Public consumers should import from `../local-rpc.ts`.
 */

export {
  LocalRpcUnavailableError,
  createSparkDaemonLocalEventBus,
  localRpcSocketPath,
  type LocalDaemonRestartResult,
  type LocalDaemonStatusResult,
  type LocalDaemonStopResult,
  type LocalHumanInteractionListParams,
  type LocalHumanInteractionListResult,
  type LocalHumanInteractionRespondParams,
  type LocalHumanInteractionRespondResult,
  type LocalInvocationListResult,
  type LocalInvocationRetentionPreviewResult,
  type LocalInvocationRetryResult,
  type LocalRpcServer,
  type LocalTurnCancelRequest,
  type LocalTurnCancelResult,
  type LocalTurnResult,
  type LocalTurnStatusResult,
  type LocalTurnStreamResult,
  type LocalTurnSubmitResult,
  type LocalWorkspaceClientAttachRequest,
  type LocalWorkspaceClientHeartbeatRequest,
  type LocalWorkspaceClientResult,
  type LocalWorkspaceEnsureLocalRequest,
  type LocalWorkspaceExecutorEnsureRequest,
  type LocalWorkspaceRegisterRequest,
  type LocalWorkspaceRelocateRequest,
  type LocalWorkspaceRelocateResult,
  type LocalWorkspaceLifecycleMutation,
  type LocalWorkspaceLifecycleMutationResult,
  type SparkDaemonLocalEventBus,
  type WorkspaceListResult,
} from "./types.ts";

export { handleLocalRpcLine } from "./dispatch.ts";
export { parseSparkDaemonLifecycleSnapshot } from "./results.ts";
export { startLocalRpcServer } from "./transport.ts";
export {
  requestChannelConfigure,
  requestChannelNotify,
  requestChannelReload,
  requestChannelStatus,
  requestDaemonRestart,
  requestDaemonStatus,
  requestDaemonStop,
  requestHumanInteractionList,
  requestHumanInteractionRespond,
  requestProviderAuthImportPi,
  requestProviderAuthLogout,
  requestProviderAuthOAuthCancel,
  requestProviderAuthOAuthRespond,
  requestProviderAuthOAuthStart,
  requestProviderAuthOAuthStatus,
  requestProviderAuthSetApiKey,
  requestProviderAuthSnapshot,
  requestLoopRestart,
  requestLoopControl,
  requestLoopSchedule,
  requestLoopStart,
  requestLoopStatus,
  requestLoopStop,
  requestLoopWake,
  requestSessionSnapshot,
  requestTurnCancel,
  requestTurnStatus,
  requestTurnStream,
  requestTurnSubmit,
  requestUplinkPark,
  requestUplinkPrefer,
  requestUplinkStatus,
  requestUplinkUnpark,
  requestWorkspaceAttach,
  requestWorkspaceClientAttach,
  requestWorkspaceClientHeartbeat,
  requestWorkspaceClientRelease,
  requestWorkspaceEnsureLocal,
  requestWorkspaceExecutorEnsure,
  requestWorkspaceList,
  requestWorkspaceLifecycle,
  requestWorkspaceRegister,
  requestWorkspaceRelocate,
  requestWorkspaceStop,
} from "./client.ts";

export {
  createDaemonSessionRegistry,
  createSerializedDaemonSessionRegistry,
  type DaemonSessionRegistry,
} from "../session-registry.ts";
