name: "CI - Dependency Audit"

on:
  pull_request:
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci-dependency-audit.yml"
      - "apps/*/package.json"
      - "package.json"
      - "packages/*/package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
  schedule:
    - cron: "37 2 * * 1"
  workflow_dispatch:

concurrency:
  group: ci-dependency-audit-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  pull-request-dependencies:
    name: New Dependency Vulnerabilities
    if: github.event_name == 'pull_request'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@8deb546fdb875b9996d27d4950be7312dac076a1 # v2.5.0
    with:
      scan-args: |-
        --lockfile=pnpm-lock.yaml
      upload-sarif: false

  complete-dependencies:
    name: Complete Dependency Vulnerability Audit
    if: github.event_name != 'pull_request'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8deb546fdb875b9996d27d4950be7312dac076a1 # v2.5.0
    with:
      scan-args: |-
        --lockfile=pnpm-lock.yaml
