name: "CI - Pre-commit Checks"

on:
  pull_request:
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ci-pre-commit-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/spark-node-setup
      - run: pnpm exec prek run --all-files --skip spark-check-fix
