name: "CI - Process Tests"

on:
  pull_request:
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ci-process-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  process:
    name: Process Tests (${{ matrix.name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu
            os: ubuntu-latest
          - name: macOS
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/spark-node-setup
      - run: pnpm run test:process:source
